version: '3.8'
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reverse_coding
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build: ./server
    command: npm run dev
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/reverse_coding
      - JUDGE0_URL=${JUDGE0_URL}
      - JUDGE0_KEY=${JUDGE0_KEY}
    depends_on:
      - db

volumes:
  db-data:
